### PR TITLE
Use Vanilla Webpack

### PR DESCRIPTION
**Pull request by mcclayton**
Switching to use vanilla webpack and fix issues with shipping the compiled/transpiled package.

### CODE REVIEW

**Comment by mcclayton** [comment]
Finally got things to work now. I can clean up the commit history tomorrow if that bothers you, was doing a lot of testing: 😅

**Comment by alex-cory** [comment]
I can just squash and merge. Let me check it out though after work 😄

**Comment by alex-cory** [comment]
I'm pretty sure I going to make a github page for this, so I might add the `App.js` back in :) If you're free tonight and wanna pair or something, let me know!

**Comment by mcclayton** [comment]
Ok sounds good! Feel free to also just pick and choose what you want out of this PR then and put the changes into a different branch if you'd like. I'm actually just leaving for a vacation or I'd take you up on that 😅

**Comment by alex-cory** [comment]
All good! I'll check it out tonight in more detail. Thanks for contributing! :) Looks like this project is picking up more steam. 10 ⭐️s just today

**Comment by alex-cory** [comment]
I would love to switch to Parcel, but this works for now :)

**Comment by alex-cory** [comment]
It's so beautiful 😍

**Pull request merged**
